_wandb:
    value:
        cli_version: 0.21.3
        e:
            6ljqmi96csxf5qnahahk6tst4nhtcb5j:
                args:
                    - --node-ip-address=172.28.177.94
                    - --node-manager-port=33275
                    - --object-store-name=/disk3/yiran/yaoqi/ray_tmp/ray/session_2025-09-10_12-27-36_845376_3625887/sockets/plasma_store
                    - --raylet-name=/disk3/yiran/yaoqi/ray_tmp/ray/session_2025-09-10_12-27-36_845376_3625887/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=63711
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=55354
                    - --gcs-address=172.28.177.94:53498
                    - --session-name=session_2025-09-10_12-27-36_845376_3625887
                    - --temp-dir=/disk3/yiran/yaoqi/ray_tmp/ray
                    - --webui=127.0.0.1:8265
                    - --cluster-id=caa54725e327942c411dd433140eb9429b364d752a5fde45c5001efa
                    - --startup-token=256
                    - --worker-launch-time-ms=1757507262170
                    - --node-id=7c0ae8b5ead05cdccf4b4b8bfd1d6bbc03f19fb9543f705914e506cb
                    - --runtime-env-hash=-1624044036
                    - --enable-resource-isolation=false
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1880103190528"
                        used: "1724367998976"
                email: shadowapplese@gmail.com
                executable: /home/yiran/miniconda3/envs/shortrl/bin/python3
                git:
                    commit: f519a315e3454849f25d574f3d74af5527d07854
                    remote: https://github.com/lblankl/Short-RL.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-2922e67b-0900-4c64-fe95-94c2713fe859
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-11750985-0f1a-c9c3-112e-07931e88905d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-92effd43-a936-4134-9efe-87a0f9a65135
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-0a3dab48-1127-d79f-8c45-b0193134af7e
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-c65a533f-c2b5-8ec1-f325-03c3719c36b1
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-7afd9180-f2fd-e76f-ae65-65ee06b26c49
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-67d30557-f97c-291c-b15b-74501dcfec5a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-78f68a65-4de8-5638-e55d-d8d26692f03b
                host: dgx.d2.comp.nus.edu.sg
                memory:
                    total: "2164271816704"
                os: Linux-5.4.0-208-generic-x86_64-with-glibc2.31
                program: /home/yiran/miniconda3/envs/shortrl/lib/python3.10/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.10.18
                root: /home/yiran/yaoqi_workplace/Short-RL/deepscaler
                startedAt: "2025-09-10T12:28:57.029286Z"
                writerId: 6ljqmi96csxf5qnahahk6tst4nhtcb5j
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 53
                - 71
                - 95
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 53
                - 71
                - 95
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.3
            "6": 4.56.1
            "12": 0.21.3
            "13": linux-x86_64
actor_rollout_ref:
    value:
        actor:
            checkpoint:
                load_contents:
                    - model
                    - optimizer
                    - extra
                save_contents:
                    - model
                    - optimizer
                    - extra
            clip_ratio: 0.2
            clip_ratio_c: 3
            clip_ratio_high: 0.2
            clip_ratio_low: 0.2
            entropy_checkpointing: false
            entropy_coeff: 0
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: true
                param_offload: true
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            grad_clip: 1
            kl_loss_coef: 0.001
            kl_loss_type: low_var_kl
            loss_agg_mode: token-mean
            optim:
                lr: 1e-06
                lr_warmup_steps: -1
                lr_warmup_steps_ratio: 0
                min_lr_ratio: 0
                num_cycles: 0.5
                total_training_steps: 2220
                warmup_style: constant
                weight_decay: 0.01
            policy_loss:
                clip_cov_lb: 1
                clip_cov_ratio: 0.0002
                clip_cov_ub: 5
                kl_cov_ratio: 0.0002
                loss_mode: vanilla
                ppo_kl_coef: 0.1
            ppo_epochs: 1
            ppo_max_token_len_per_gpu: 32768
            ppo_micro_batch_size: 32
            ppo_micro_batch_size_per_gpu: null
            ppo_mini_batch_size: 64
            profiler:
                all_ranks: false
                discrete: false
                ranks: null
            shuffle: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_dynamic_bsz: true
            use_kl_loss: true
            use_torch_compile: true
        hybrid_engine: true
        model:
            custom_chat_template: null
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            external_lib: null
            fused_kernel_options:
                impl_backend: torch
            lora_alpha: 16
            lora_rank: 0
            path: Qwen/Qwen2.5-Math-1.5B-Instruct
            target_modules: all-linear
            trust_remote_code: false
            use_fused_kernels: false
            use_liger: false
            use_remove_padding: true
            use_shm: false
        ref:
            entropy_checkpointing: false
            entropy_from_logits_with_chunking: false
            fsdp_config:
                forward_prefetch: false
                param_offload: true
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            log_prob_max_token_len_per_gpu: 32768
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: null
            log_prob_use_dynamic_bsz: true
            profiler:
                all_ranks: false
                discrete: false
                ranks: null
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_torch_compile: true
        rollout:
            calculate_log_probs: false
            disable_log_stats: true
            do_sample: true
            dtype: bfloat16
            enable_chunked_prefill: true
            enforce_eager: false
            engine_kwargs:
                sglang:
                    attention_backend: null
                vllm:
                    disable_mm_preprocessor_cache: false
                    swap_space: null
            free_cache_engine: false
            gpu_memory_utilization: 0.85
            ignore_eos: false
            layered_summon: false
            load_format: dummy_dtensor
            log_prob_max_token_len_per_gpu: 32768
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: null
            log_prob_use_dynamic_bsz: true
            max_model_len: null
            max_num_batched_tokens: 8192
            max_num_seqs: 1024
            mode: sync
            multi_stage_wake_up: false
            multi_turn:
                completion_callback: null
                enable: false
                format: hermes
                interaction_config_path: null
                max_assistant_turns: null
                max_user_turns: null
                tokenization_sanity_check_mode: strict
                tool_config_path: null
                use_inference_chat_template: false
            "n": 8
            name: vllm
            profiler:
                all_ranks: false
                discrete: false
                ranks: null
            prompt_length: 1024
            response_length: 2048
            temperature: 0.6
            tensor_model_parallel_size: 1
            top_k: -1
            top_p: 1
            use_fire_sampling: false
            val_kwargs:
                do_sample: false
                "n": 1
                temperature: 0
                top_k: -1
                top_p: 1
            validate_roll_out_max_length: 9216
algorithm:
    value:
        acc_tolerance: 0.05
        adv_estimator: grpo
        gamma: 1
        kl_ctrl:
            horizon: 10000
            kl_coef: 0.001
            target_kl: 0.1
            type: fixed
        kl_penalty: kl
        lam: 1
        length_tolerance: 100
        norm_adv_by_std_in_grpo: true
        pf_ppo:
            reweight_method: pow
            weight_pow: 2
        use_kl_in_reward: false
        use_pf_ppo: false
critic:
    value:
        checkpoint:
            load_contents:
                - model
                - optimizer
                - extra
            save_contents:
                - model
                - optimizer
                - extra
        cliprange_value: 0.5
        forward_max_token_len_per_gpu: 32768
        forward_micro_batch_size: null
        forward_micro_batch_size_per_gpu: null
        grad_clip: 1
        loss_agg_mode: token-mean
        model:
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            lora_alpha: 16
            lora_rank: 0
            path: ~/models/deepseek-llm-7b-chat
            target_modules: all-linear
            tokenizer_path: Qwen/Qwen2.5-Math-1.5B-Instruct
            trust_remote_code: false
            use_remove_padding: false
            use_shm: false
        optim:
            lr: 1e-05
            lr_warmup_steps_ratio: 0
            min_lr_ratio: null
            total_training_steps: 2220
            warmup_style: constant
            weight_decay: 0.01
        ppo_epochs: 1
        ppo_max_token_len_per_gpu: 32768
        ppo_micro_batch_size: null
        ppo_micro_batch_size_per_gpu: null
        ppo_mini_batch_size: 64
        profiler:
            all_ranks: false
            discrete: false
            ranks: null
        rollout_n: 8
        shuffle: false
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
custom_reward_function:
    value:
        name: compute_score
        path: null
data:
    value:
        custom_cls:
            name: null
            path: null
        filter_overlong_prompts: false
        filter_overlong_prompts_workers: 1
        image_key: images
        max_prompt_length: 1024
        max_response_length: 2048
        prompt_key: prompt
        return_full_prompt: false
        return_raw_chat: false
        return_raw_input_ids: false
        reward_fn_key: data_source
        shuffle: true
        tokenizer: null
        train_batch_size: 128
        train_files: /home/yiran/yaoqi_workplace/Short-RL/deepscaler/deepscaler/data/orzmath/train.parquet
        truncation: error
        trust_remote_code: false
        use_shm: false
        val_batch_size: 128
        val_files:
            - /home/yiran/yaoqi_workplace/Short-RL/deepscaler/deepscaler/data/orzmath/aime.parquet
            - /home/yiran/yaoqi_workplace/Short-RL/deepscaler/deepscaler/data/orzmath/amc.parquet
            - /home/yiran/yaoqi_workplace/Short-RL/deepscaler/deepscaler/data/orzmath/math.parquet
            - /home/yiran/yaoqi_workplace/Short-RL/deepscaler/deepscaler/data/orzmath/minerva.parquet
            - /home/yiran/yaoqi_workplace/Short-RL/deepscaler/deepscaler/data/orzmath/olympiad_bench.parquet
        validation_shuffle: false
        video_key: videos
ray_init:
    value:
        num_cpus: null
        timeline_json_file: null
reward_model:
    value:
        enable: false
        forward_max_token_len_per_gpu: 32768
        launch_reward_fn_async: false
        max_length: null
        micro_batch_size: null
        micro_batch_size_per_gpu: null
        model:
            external_lib: null
            fsdp_config:
                forward_prefetch: false
                fsdp_size: -1
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            input_tokenizer: Qwen/Qwen2.5-Math-1.5B-Instruct
            path: ~/models/FsfairX-LLaMA3-RM-v0.1
            trust_remote_code: false
            use_fused_kernels: false
            use_remove_padding: false
            use_shm: false
        profiler:
            all_ranks: false
            discrete: false
            ranks: null
        reward_manager: naive
        sandbox_fusion:
            max_concurrent: 64
            memory_limit_mb: 1024
            url: null
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: true
trainer:
    value:
        balance_batch: true
        controller_nsight_options:
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            trace: cuda,nvtx,cublas,ucx
        critic_warmup: 0
        default_hdfs_dir: null
        default_local_dir: /home/yiran/yaoqi_workplace/Short-RL/deepscaler/Qwen-short
        del_local_ckpt_after_load: false
        device: cuda
        experiment_name: Qwen-short
        log_val_generations: 0
        logger:
            - console
            - wandb
        max_actor_ckpt_to_keep: null
        max_critic_ckpt_to_keep: null
        n_gpus_per_node: 1
        nnodes: 1
        profile_steps: null
        project_name: DeepScaler
        ray_wait_register_center_timeout: 300
        resume_from_path: null
        resume_mode: auto
        reward_type: ShortRL
        rollout_data_dir: null
        save_freq: 100
        test_freq: 20
        total_epochs: 5
        total_training_steps: null
        val_before_train: true
        val_only: false
        validation_data_dir: null
        worker_nsight_options:
            capture-range: cudaProfilerApi
            capture-range-end: null
            cuda-graph-trace: graph
            cuda-memory-usage: "true"
            kill: none
            trace: cuda,nvtx,cublas,ucx
